### ISSUE TITLE
@react-libraries/use-ssr のリンクについて

### ISSUE THREAD

**Issue by seiei-sogen** [SoraKumo001/zenn#1]
初めまして、お世話になります。

記事『Next.jsでSSRを限界まで簡単に実現する』にあります、
@react-libraries/use-ssr の部分がリンク切れになっております。

こちら、@react-libraries/use-ssr が公開終了したということでしょうか。
代替のライブラリを教えていただけますとありがたいです。

**Comment by SoraKumo001** [comment]
リポジトリがPrivate設定になっていました
Publicに直したので見られるようになったと思います

ちなみにnpmでは以下の場所で公開しています
https://www.npmjs.com/package/@react-libraries/use-ssr

**Comment by seiei-sogen** [comment]
承知致しました。
確認したところ、見られました。
ありがとうございます！
issue、close致します。
